### ISSUE TITLE
Feature Request: I think the color of the keys are too bright

### ISSUE THREAD

**Issue by CrackheadoooObsidianUserooo** [Quorafind/Obsidian-Surfing-Key#1]
### Feature Requested

As the title

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by tprotopopescu** [comment]
Yes +1! The key bubbles are white font on yellow background, it is very hard to read; sometimes the font turns black after you press one key and only the possible completions are left displayed.

**Comment by CrackheadoooObsidianUserooo** [comment]
> Yes +1! The key bubbles are white font on yellow background, it is very hard to read; sometimes the font turns black after you press one key and only the possible completions are left displayed.

Ive just changed the css of this file so i made it more visible. I have low programming skills. I changed the css with vscode

![image](https://github.com/Quorafind/Obsidian-Surfing-Key/assets/121588624/9893e827-4cb1-4e01-a362-1afb59da18fa)

/*

This CSS file will be included with your plugin, and
available in the app when your plugin is enabled.

If your plugin does not need CSS, delete this file.

*/

.surfing-key-overlay {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background-color: rgba(0, 0, 0, 0.1);
	z-index: 99999;
	pointer-events: none;
}

.surfing-key-string {
	position: absolute;
	z-index: 100000;
	pointer-events: none;
	color: var(--color-base-90);
	font-size: 12px;

	background-color: var(--color--base-50);
	padding: 0px 2px 0px 2px;
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ff8585), color-stop(100%,#fd0000));
	border: solid 1px #C38A22;
	border-radius: 3px;
	box-shadow: 0px 3px 7px 0px rgba(0, 0, 0, 0.3);
	width: auto;
	margin-right: 2px;
}

#inputDisplay {
	position: absolute;
	bottom: 0;
	left: 50%;
	transform: translateX(-50%);
	color: var(--color-base-90);
	font-size: var(--size-4-8);
	z-index: 100001;
}

**Comment by adriangonzalez** [comment]
Thanks for the comment @CrackheadoooObsidianUserooo . Now I just need to find where the css file is located when installing on Windows using BRAT lol 😅

**Comment by ianTevesAcc** [comment]
I edited my css and this is how I made mine look.

```css
.modal-container.mod-dim.surfing-key-overlay .surfing-key-string {
  font-weight: bold;
  font-size: 10px;
  color: white;
  background: gray !important;
  border-radius: 5px !important;
  padding: 0px 4px 0px 4px !important;
  border: 1px solid white !important;
}
```

![image](https://github.com/Quorafind/Obsidian-Surfing-Key/assets/105651670/1a591f27-0b93-4db8-b2ac-c6202c9bb725)

Each of these classes below should be something you can edit.
```css
.surfing-key-string {
    position: absolute;
    z-index: 100000;
    pointer-events: none;
    color: var(--color-base-90);
    font-size: 12px;
    background-color: var(--color--base-50);
    padding: 0px 2px 0px 2px;
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFF785), color-stop(100%,#FFC542));
    border: solid 1px #C38A22;
    border-radius: 3px;
    box-shadow: 0px 3px 7px 0px rgba(0, 0, 0, 0.3);
    width: auto;
    margin-right: 2px;
}
```
